FROM nginx

MAINTAINER Ícaro Heimig

RUN apt-get -y update && \
    apt-get -y install git && \
    mkdir -p /archive

RUN git clone https://github.com/easyac/apidocs /var/www/html

COPY nginx.dev.conf /etc/nginx/nginx.conf
